name: test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        A: [AA, AB, AC]
        B: [BA, BB, BC]
        exclude:
         - A: AA
           B: [BA, BC]

    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          A: ${{ matrix.A }}
          B: ${{ matrix.B }}
        run: echo $A $B
